### PR TITLE
Make the file name the same as the class name.

### PR DESCRIPTION
**Pull request by chiroruxx**
Make the file name the same as the class name.

With composer2.0, when using PSR-4 autoload, the file name and class name must be the same.

### CODE REVIEW

**Review by Shohei-Japan — APPROVED** [review]

**Review by scouterinc — APPROVED** [review]

**Comment by kotamat** [comment]
@chiroruxx 
Thx! the master branch follows over Laravel 7, so could you also make PR to `under-laravel6` branch?

**Comment by chiroruxx** [comment]
I changed this PR to merge to branch `under-laravel6` !

**Comment by chiroruxx** [comment]
I make PR https://github.com/kotamat/laravel-apispec-generator/pull/9 .

**Comment by chiroruxx** [comment]
I made 2 PRs

- to master https://github.com/kotamat/laravel-apispec-generator/pull/9
- to under-laravel6 https://github.com/kotamat/laravel-apispec-generator/pull/10

**Pull request closed without merging**
